;;; vc-jj-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from project-jj.el

(cl-defmethod project-files :around ((project (head vc)) &optional dirs) "Return a list of files in directories DIRS in PROJECT." (if (eq (cadr project) 'JJ) (let* ((default-directory (expand-file-name (project-root project))) (args (cons "--" (mapcar #'file-relative-name dirs))) (files (apply #'process-lines "jj" "file" "list" args))) (mapcar #'expand-file-name files)) (cl-call-next-method)))
(with-eval-after-load 'project (add-to-list 'project-vc-backend-markers-alist '(JJ . ".jj")))


;;; Generated autoloads from vc-jj.el

(add-to-list 'vc-handled-backends 'JJ)
 (defun vc-jj-registered (file)
  "Return non-nil if FILE is registered with jj."
  (if (and (vc-find-root file ".jj")   ; Short cut.
           (executable-find "jj"))
      (progn
        (load "vc-jj" nil t)
        (vc-jj-registered file))))
(add-to-list 'auto-mode-alist '("\\.jjdescription\\'" . log-edit-mode))
(add-hook 'vc-log-mode-hook #'vc-jj-ensure-log-edit-callback)
(add-hook 'log-edit-mode-hook #'vc-jj-ensure-log-edit-callback)
(autoload 'vc-jj-ensure-log-edit-callback "vc-jj" "\
Set up `log-edit-callback' when editing jj change descriptions.")
(register-definition-prefixes "vc-jj" '("vc-jj-"))


;;; Generated autoloads from vc-jj-tests.el

(register-definition-prefixes "vc-jj-tests" '("vc-jj-test-"))

;;; End of scraped data

(provide 'vc-jj-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vc-jj-autoloads.el ends here
