;;; d2-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from d2-ts-compile.el

(autoload 'd2-ts-mode-compile "d2-ts-compile" "\
Compile the current D2 file.
The output file is placed alongside the source with the extension
determined by `d2-ts-mode-output-format'." t)
(autoload 'd2-ts-mode-compile-buffer "d2-ts-compile" "\
Compile the current buffer contents as D2.
Writes buffer contents to a temporary file and compiles it.
Useful for unsaved buffers." t)
(autoload 'd2-ts-mode-compile-region "d2-ts-compile" "\
Compile the region between BEG and END as D2.
Writes the region to a temporary file and compiles it.

(fn BEG END)" t)
(autoload 'd2-ts-mode-watch "d2-ts-compile" "\
Start d2 in watch mode for the current file.
When `d2-ts-mode-watch-method' is `browser', d2 opens a browser tab.
When it is `emacs', the browser is suppressed and the output image
is displayed in an Emacs side window with `auto-revert-mode'.
If a watch process is already running, it is restarted." t)
(autoload 'd2-ts-mode-watch-stop "d2-ts-compile" "\
Stop the d2 watch process for the current buffer.
Also closes the Emacs preview window if it was opened." t)
(autoload 'd2-ts-mode-preview "d2-ts-compile" "\
Toggle an Emacs image preview of the current D2 file.
First invocation compiles the file and displays the output image
in a side window with `auto-revert-mode'.  An `after-save-hook'
is added so saving the source automatically recompiles.
Calling again closes the preview and removes the hook." t)
(register-definition-prefixes "d2-ts-compile" '("d2-ts-"))


;;; Generated autoloads from d2-ts-font-lock.el

(register-definition-prefixes "d2-ts-font-lock" '("d2-ts-mode--"))


;;; Generated autoloads from d2-ts-imenu.el

(register-definition-prefixes "d2-ts-imenu" '("d2-ts-"))


;;; Generated autoloads from d2-ts-indent.el

(register-definition-prefixes "d2-ts-indent" '("d2-ts-mode--indent-rules"))


;;; Generated autoloads from d2-ts-mode.el

(autoload 'd2-ts-mode-reinstall-grammar "d2-ts-mode" "\
Reinstall the D2 tree-sitter grammar." t)
(autoload 'd2-ts-mode "d2-ts-mode" "\
Major mode for editing D2 diagrams, powered by tree-sitter.

\\{d2-ts-mode-map}

(fn)" t)
(register-definition-prefixes "d2-ts-mode" '("d2-ts-mode-"))

;;; End of scraped data

(provide 'd2-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; d2-ts-mode-autoloads.el ends here
