;;; org-draw-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-draw.el

(autoload 'org-draw-server-start "org-draw" "\
Start the org-draw HTTP server." t)
(autoload 'org-draw-server-stop "org-draw" "\
Stop the org-draw HTTP server." t)
(autoload 'org-draw-edit "org-draw" "\
Explicitly re-edit the org-draw figure at point.
Signal a clear error if point is on a foreign PNG (no embedded strokes, so not
re-editable) or not on a figure at all." t)
(autoload 'org-draw-setup "org-draw" "\
Start the server and show the receiver URL (copied to the clipboard).
When `org-draw-require-pairing' is non-nil, also generate and show a 6-digit
pairing code." t)
(autoload 'org-draw "org-draw" "\
Draw into the org buffer at point.  On an org-draw figure link, re-edit it.
Both new figures and edits open the web canvas at GET /canvas: a receiver tab
you keep open long-polls and picks up the request (or set
`org-draw-web-open-function' to also open it on the machine running Emacs)." t)
 (autoload 'org-draw-menu "org-draw" nil t)
(register-definition-prefixes "org-draw" '("org-draw-"))

;;; End of scraped data

(provide 'org-draw-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-draw-autoloads.el ends here
