;;; flash-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flash.el

(autoload 'flash-jump "flash" "\
Start flash jump session.
Type characters to search, then press a label to jump.
Press RET to jump to first match, ESC to cancel." t)
(autoload 'flash-jump-continue "flash" "\
Continue flash jump with the last search pattern.
If no previous pattern exists, starts a new search." t)
(register-definition-prefixes "flash" '("flash-"))


;;; Generated autoloads from flash-char.el

(autoload 'flash-char-find "flash-char" "\
Jump forward to CHAR on current line.
COUNT is used only for direction: negative means reverse search
(for evil repeat compatibility), not for repetition.
With labels enabled, shows labels for multiple matches.

(fn COUNT CHAR)" t)
(autoload 'flash-char-find-to "flash-char" "\
Jump forward to before CHAR on current line.
COUNT is used only for direction: negative means reverse search
(for evil repeat compatibility), not for repetition.
With labels enabled, shows labels for multiple matches.

(fn COUNT CHAR)" t)
(autoload 'flash-char-find-backward "flash-char" "\
Jump backward to CHAR on current line.
COUNT is used only for direction: negative means forward search
(for evil repeat compatibility), not for repetition.
With labels enabled, shows labels for multiple matches.

(fn COUNT CHAR)" t)
(autoload 'flash-char-find-to-backward "flash-char" "\
Jump backward to after CHAR on current line.
COUNT is used only for direction: negative means forward search
(for evil repeat compatibility), not for repetition.
With labels enabled, shows labels for multiple matches.

(fn COUNT CHAR)" t)
(autoload 'flash-char-repeat "flash-char" "\
Repeat last char motion in same direction." t)
(autoload 'flash-char-repeat-reverse "flash-char" "\
Repeat last char motion in opposite direction." t)
(register-definition-prefixes "flash-char" '("flash-char-"))


;;; Generated autoloads from flash-evil.el

(autoload 'flash-evil-jump "flash-evil" "\
Flash jump as evil motion.
Works with operators: d s <target> deletes to target.
In visual mode: extends selection to target.

(fn &optional COUNT)" t)
(autoload 'flash-evil-setup "flash-evil" "\
Set up evil keybindings for flash.
Binds `gs' in normal, visual, motion, and operator states.
When CHAR-MOTIONS is non-nil, also replace f/t/F/T with flash versions.

(fn &optional CHAR-MOTIONS)" t)
(register-definition-prefixes "flash-evil" '("flash-evil--define-motion"))


;;; Generated autoloads from flash-highlight.el

(register-definition-prefixes "flash-highlight" '("flash-"))


;;; Generated autoloads from flash-isearch.el

(defvar flash-isearch-mode nil "\
Non-nil if Flash-Isearch mode is enabled.
See the `flash-isearch-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `flash-isearch-mode'.")
(custom-autoload 'flash-isearch-mode "flash-isearch" nil)
(autoload 'flash-isearch-mode "flash-isearch" "\
Show flash labels during incremental search.

Works with both evil-ex-search and isearch.

This is a global minor mode.  If called interactively, toggle the
`Flash-Isearch mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='flash-isearch-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "flash-isearch" '("flash-isearch-"))


;;; Generated autoloads from flash-jump.el

(register-definition-prefixes "flash-jump" '("flash-"))


;;; Generated autoloads from flash-label.el

(register-definition-prefixes "flash-label" '("flash-"))


;;; Generated autoloads from flash-search.el

(register-definition-prefixes "flash-search" '("flash-"))


;;; Generated autoloads from flash-state.el

(register-definition-prefixes "flash-state" '("flash-state-c"))


;;; Generated autoloads from flash-treesitter.el

(autoload 'flash-treesitter "flash-treesitter" "\
Show labels for treesitter nodes at point.
Press a label to select that node's range.
With evil-mode, enters visual state for the selection." t)
(defalias 'flash-treesitter-evil #'flash-treesitter "\
Deprecated alias for `flash-treesitter'.
`flash-treesitter' now auto-detects evil-mode.")
(register-definition-prefixes "flash-treesitter" '("flash-treesitter-"))

;;; End of scraped data

(provide 'flash-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flash-autoloads.el ends here
